import * as XLSX from 'xlsx';
import { formatDate, formatStatus } from './helpers';

/** Capitalize first letter */
const cap = s => (s ? s.charAt(0).toUpperCase() + s.slice(1) : '');

/** Format status nicely */
const fmtStatus = s => (s === 'in_progress' ? 'In Progress' : cap(s));

/**
 * Export report to Excel
 * Mirrors the UI report layout:
 *   Sheet 1 – Summary  (title, filter info, stat boxes)
 *   Sheet 2 – Tasks    (full task table with all columns)
 */
export const exportToExcel = (
  reportData,
  appliedFilters = {},
  generatedBy = '',
) => {
  const { tasks = [], summary = {} } = reportData;
  const wb = XLSX.utils.book_new();

  /* ─────────────────────────────────────────
     SHEET 1 – Summary
  ───────────────────────────────────────── */
  const filterLine = buildFilterLine(appliedFilters);
  const now = new Date().toLocaleString();

  const summaryRows = [
    ['Task Management Report'],
    [''],
    ['Generated By', generatedBy || '—'],
    ['Generated At', now],
    ['Filters Applied', filterLine],
    [''],
    ['── Summary Statistics ──'],
    ['Metric', 'Value'],
    ['Total Tasks', summary.totalTasks ?? 0],
    ['Completed', summary.completedTasks ?? 0],
    ['In Progress', summary.inProgressTasks ?? 0],
    ['Pending', summary.pendingTasks ?? 0],
    ['Overdue', summary.overdueTasks ?? 0],
    ['Completion Rate', `${summary.completionRate ?? 0}%`],
  ];

  const summaryWs = XLSX.utils.aoa_to_sheet(summaryRows);

  // Column widths
  summaryWs['!cols'] = [{ wch: 22 }, { wch: 40 }];

  // Merge title cell across 2 columns
  summaryWs['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 1 } }];

  // Style title row (bold, large)
  styleCell(summaryWs, 'A1', { bold: true, sz: 16 });
  styleCell(summaryWs, 'A7', { bold: true });
  styleCell(summaryWs, 'A8', { bold: true });
  styleCell(summaryWs, 'B8', { bold: true });

  XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');

  /* ─────────────────────────────────────────
     SHEET 2 – Tasks
  ───────────────────────────────────────── */
  if (tasks.length === 0) {
    const emptyWs = XLSX.utils.aoa_to_sheet([
      ['No tasks found for the selected filters.'],
    ]);
    XLSX.utils.book_append_sheet(wb, emptyWs, 'Tasks');
  } else {
    // Header row
    const headers = [
      '#',
      'Task Title',
      'Description',
      'Assigned To',
      'Status',
      'Priority',
      'Due Date',
      'Created By',
      'Created At',
      'Completed At',
    ];

    const rows = tasks.map((task, idx) => [
      idx + 1,
      task.title || '',
      task.description || '',
      task.assigneeName || '',
      fmtStatus(task.status || ''),
      cap(task.priority || ''),
      task.dueDate ? new Date(task.dueDate).toLocaleDateString() : '',
      task.createdByName || '',
      task.createdAt ? new Date(task.createdAt).toLocaleDateString() : '',
      task.completedAt ? new Date(task.completedAt).toLocaleDateString() : '—',
    ]);

    const tasksWs = XLSX.utils.aoa_to_sheet([headers, ...rows]);

    // Column widths matching UI columns
    tasksWs['!cols'] = [
      { wch: 4 }, // #
      { wch: 30 }, // Title
      { wch: 40 }, // Description
      { wch: 20 }, // Assignee
      { wch: 14 }, // Status
      { wch: 12 }, // Priority
      { wch: 14 }, // Due Date
      { wch: 20 }, // Created By
      { wch: 14 }, // Created At
      { wch: 14 }, // Completed At
    ];

    // Bold header row
    headers.forEach((_, ci) => {
      const addr = XLSX.utils.encode_cell({ r: 0, c: ci });
      styleCell(tasksWs, addr, { bold: true });
    });

    // Freeze header row
    tasksWs['!freeze'] = { xSplit: 0, ySplit: 1 };

    XLSX.utils.book_append_sheet(wb, tasksWs, 'Tasks');
  }

  /* ─────────────────────────────────────────
     Save
  ───────────────────────────────────────── */
  const filename = `task-report-${new Date().toISOString().slice(0, 10)}.xlsx`;
  XLSX.writeFile(wb, filename);
};

/* ── helpers ── */

function buildFilterLine(filters = {}) {
  const parts = [];
  if (filters.startDate) parts.push(`From: ${filters.startDate}`);
  if (filters.endDate) parts.push(`To: ${filters.endDate}`);
  if (filters.status && filters.status !== 'all')
    parts.push(`Status: ${fmtStatus(filters.status)}`);
  if (filters.priority && filters.priority !== 'all')
    parts.push(`Priority: ${cap(filters.priority)}`);
  return parts.length ? parts.join('  |  ') : 'All tasks (no filters)';
}

/** Apply basic font style to a cell (xlsx-js-style not required — uses raw cell format) */
function styleCell(ws, addr, { bold = false, sz = 11 } = {}) {
  if (!ws[addr]) ws[addr] = { t: 's', v: '' };
  ws[addr].s = {
    font: { bold, sz },
  };
}

/**
 * Export report to PDF  (kept for backward compatibility)
 */
export const exportToPDF = (reportData, filename = 'task-report') => {
  // Dynamic import to avoid SSR issues
  import('jspdf').then(({ default: jsPDF }) => {
    import('jspdf-autotable').then(() => {
      const { tasks = [], summary = {} } = reportData;
      const doc = new jsPDF({ orientation: 'landscape' });

      doc.setFontSize(18);
      doc.text('Task Management Report', 14, 18);

      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 26);

      // Summary
      doc.setFontSize(12);
      doc.text('Summary', 14, 36);
      doc.setFontSize(10);
      const s = summary;
      doc.text(
        `Total: ${s.totalTasks ?? 0}   Completed: ${s.completedTasks ?? 0}   In Progress: ${s.inProgressTasks ?? 0}   Pending: ${s.pendingTasks ?? 0}   Completion Rate: ${s.completionRate ?? 0}%`,
        14,
        44,
      );

      // Table
      const tableData = tasks.map((task, idx) => [
        idx + 1,
        task.title,
        task.assigneeName,
        fmtStatus(task.status),
        cap(task.priority),
        task.dueDate ? new Date(task.dueDate).toLocaleDateString() : '',
        task.description?.substring(0, 50) +
          (task.description?.length > 50 ? '…' : ''),
      ]);

      doc.autoTable({
        startY: 52,
        head: [
          [
            '#',
            'Title',
            'Assignee',
            'Status',
            'Priority',
            'Due Date',
            'Description',
          ],
        ],
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [30, 64, 175] },
        columnStyles: { 6: { cellWidth: 60 } },
      });

      doc.save(`${filename}-${new Date().toISOString().slice(0, 10)}.pdf`);
    });
  });
};
